# Copyright 2023 The Milton Hirsch Institute, B.V.
# SPDX-License-Identifier: Apache-2.0

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-added-large-files
        - id: check-executables-have-shebangs
        - id: check-json
        - id: check-merge-conflict
        - id: check-symlinks
        - id: check-toml
        - id: check-yaml
        - id: destroyed-symlinks
        - id: end-of-file-fixer
        - id: forbid-new-submodules
        - id: mixed-line-ending
        - id: pretty-format-json
        - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        files: \.(toml|yaml|yml|sh)
        args:
          - --use-current-year
      - id: insert-license
        files: \.(rs)
        args:
          - --use-current-year
          - --comment-style
          - //
      - id: insert-license
        files: \.(md)
        args:
          - --use-current-year
          - --comment-style
          - "<!-- || -->"

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: fmt
