# Copyright 2023 The Milton Hirsch Institute, B.V.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "subnet-garden-core"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = "^0.2"
cidr-utils = "^0.6"
serde = "^1"

[dev-dependencies]
grcov = "^0.8"
serde_json = "^1"